[model]
type = "map"
label = "Standard Map"
dtype = "float64"

[states]
p     = 0.0
theta = 0.1

[params]
K  = 0.971635

[equations.rhs]
p     = "((p + K * sin(theta)) + pi) % (2*pi) - pi"
theta = "(theta + p + K * sin(theta)) % (2*pi)"

[meta]
title = "Standard Map (Chirikovâ€“Taylor, unwrapped)"
