[model]
type = "map"
label = "Standard Map (no wrap)"
dtype = "float64"

[states]
p     = 0.0
theta = 0.1

[params]
K  = 0.971635
pi = 3.141592653589793
# TODO: Support pi / e constants

[equations.rhs]
p     = "p + K * sin(theta)"
theta = "theta + p + K * sin(theta)"

[meta]
title = "Standard Map (Chirikovâ€“Taylor, unwrapped)"
